name: Markdown to PDF

on:
  push:
    branches:
      - main

jobs:
  convert_md_to_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc weasyprint fonts-noto-cjk

      - name: Create style.css with advanced styles
        run: |
          cat <<EOF > style.css
          @page {
            size: A4;
            margin: 2cm;
            @top-center {
              content: "Dotnet Resume";
              font-size: 12pt;
              color: #555;
            }
            @bottom-center {
              content: counter(page);
              font-size: 10pt;
              color: #555;
            }
          }
          body {
            font-family: 'Noto Sans CJK SC', sans-serif;
            font-size: 12pt;
            line-height: 1.5;
            color: #333;
          }
          h1, h2, h3 {
            color: #2c3e50;
            margin-top: 1.5em;
          }
          h1 {
            font-size: 24pt;
            border-bottom: 2px solid #2c3e50;
            padding-bottom: 0.2em;
          }
          h2 {
            font-size: 18pt;
            border-bottom: 1px solid #ccc;
            padding-bottom: 0.1em;
          }
          a {
            color: #2980b9;
            text-decoration: none;
          }
          a:hover {
            text-decoration: underline;
          }
          ul, ol {
            margin-left: 1.5em;
          }
          code {
            background-color: #f4f4f4;
            padding: 2px 4px;
            border-radius: 4px;
          }
          pre {
            background-color: #f4f4f4;
            padding: 1em;
            border-radius: 4px;
            overflow-x: auto;
          }
          EOF

      - name: Convert MD to PDF with metadata
        run: |
          pandoc dotnet_resume.md \
            -f gfm \
            -t html5 \
            --wrap=preserve \
            -c style.css \
            --metadata title="Dotnet Resume" \
            --metadata author="Your Name" \
            --pdf-engine=weasyprint \
            -o dotnet_resume.pdf

      - name: Commit and push PDF
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add dotnet_resume.pdf
          git commit -m "Convert dotnet_resume.md to dotnet_resume.pdf"
          git push
