name: Markdown to PDF

on:
  push:
    branches:
      - main

jobs:
  convert_md_to_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc wkhtmltopdf

      - name: Convert MD to PDF
        run: |
          pandoc dotnet_resume.md -f gfm -t pdf --pdf-engine=wkhtmltopdf -o dotnet_resume.pdf

      - name: Commit and push PDF
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add dotnet_resume.pdf
          git commit -m "Convert dotnet_resume.md to dotnet_resume.pdf"
          git push
