name: Markdown to PDF

on:
  push:
    branches:
      - main

jobs:
  convert_md_to_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc weasyprint fonts-noto-cjk

      - name: Create optimized style.css
        run: |
          cat <<EOF > style.css
          @page {
            size: A4;
            margin: 1.2cm; /* 原来 2cm，减少外边距 */
            @bottom-center {
              content: counter(page);
              font-size: 9pt;
              color: #777;
            }
          }
          body {
            font-family: 'Noto Sans CJK SC', sans-serif;
            font-size: 10.5pt; /* 原来 12pt，字体略小 */
            line-height: 1.35;  /* 原来 1.5，行距更紧凑 */
            color: #333;
          }
          h1, h2, h3 {
            color: #2c3e50;
            margin-top: 1.2em; /* 原来 1.5em */
            margin-bottom: 0.5em;
          }
          h1 {
            font-size: 18pt; /* 原来 24pt */
            border-bottom: 1.5px solid #2c3e50;
            padding-bottom: 0.15em;
          }
          h2 {
            font-size: 14pt; /* 原来 18pt */
            border-bottom: 1px solid #bbb;
            padding-bottom: 0.1em;
          }
          a {
            color: #2c7bb6;
            text-decoration: none;
          }
          a:hover {
            text-decoration: underline;
          }
          ul, ol {
            margin-left: 1.2em; /* 原来 1.5em */
          }
          code {
            background-color: #f5f5f5;
            padding: 1px 3px;
            border-radius: 3px;
          }
          pre {
            background-color: #f5f5f5;
            padding: 0.8em;
            border-radius: 3px;
            overflow-x: auto;
            font-size: 9.5pt; /* 代码字体也稍微小一点 */
          }
          EOF

      - name: Convert Markdown to PDF with metadata
        run: |
          pandoc dotnet_resume.md \
            -f gfm \
            -t html5 \
            --wrap=preserve \
            -c style.css \
            --pdf-engine=weasyprint \
            -o dotnet_resume.pdf

      - name: Commit and push PDF
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add dotnet_resume.pdf
          git commit -m "Optimize PDF layout and regenerate dotnet_resume.pdf"
          git push
